# 拆分数据集

针对What的List模式，进行数据集拆分，形成具有交叉验证或者随机划分的功能。

```python
def split_dataset(X_data: pd.DataFrame, y_data: pd.DataFrame = None, test_size=0.2, n_trails=10,
                  cv: bool = False, shuffle: bool = False, random_state=None, save_dir=None):
    """
    数据划分。
    Args:
        X_data: 训练数据
        y_data: 监督数据
        test_size: 测试集比例
        n_trails: 尝试多少次寻找最佳数据集划分。
        cv: 是否是交叉验证，默认是False，当为True时，n_trails为交叉验证的n_fold
        shuffle: 是否进行随机打乱
        random_state: 随机种子
        save_dir: 信息保存的路径。

    Returns: 拆分之后的数据列表

    """
 ```

In [5]:
import os
import pandas as pd

from onekey_algo import OnekeyDS as okds
from onekey_algo.custom.components.comp2 import split_dataset

data = pd.read_csv(os.path.join(okds.ct,r'C:\Users\65476\Desktop\date\7-nRND_20patient.csv'))

rt = split_dataset(data, data['label_id'], cv=False,save_dir= r'C:\Users\65476\Desktop\date\数据划分结果',n_trails=5,test_size=0.2)
x1, x2 = rt[0]

In [6]:
x1

         ID  label_id group
10  2206602         1  test
17  2324423         1  test
6   2121571         1  test
13  2219901         1  test
4   2008128         0  test
2   2001705         0  test
5   2013903         0  test
14  2220004         1  test
9   2203027         1  test
7   2122128         1  test
16  2226545         1  test
11  2214263         1  test
3   2003684         0  test
0   1936292         0  test
15  2222688         1  test
12  2218520         1  test

In [7]:
x2

         ID  label_id group
18  2330091         1  test
1   2001004         0  test
19  2334271         1  test
8   2125062         1  test

In [ ]:
hkj